### ISSUE TITLE
reporting a few issues I have had on openSuse tumbleweed

### ISSUE THREAD

**Issue by athyla** [blueOkiris/bgrm#2] opened 2021-10-22 13:34 UTC
Hello!

I have tried to build and use bgrm on my machine, I was very excited to try it out :-)

First problem was that I could not build the kernel module and the output was not too helpful. Later on I realized that I haven't had the kernel headers to build the module. On openSuse it should be enough to install the `kernel-devel` package, but I have installed the `kernel-sources` package and that installed `kernel-devel` as dependency. After this the kernel module build was successful, perhaps mention this in the Readme.

The next problem was when running `bgrm`.
```
...
cp: cannot create regular file '.venv/lib/python3.9/site-packages/v4l2.py': No such file or directory
...
```

I verified the path manually and for some reason on my machine the path is with `python3.8` not `python3.9`:
`.venv/lib/python3.8/site-packages/v4l2.py`

So I edited that path in `bgrm.sh` and tried again, but this time it complained that `opencv-python` is not installed:

```
$> sudo ./bgrm.sh -b ~/Pictures/Teams/ISS-cupola.webp -H 720
Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/user/Applications/bgrm/bgrm/__main__.py", line 1, in <module>
    from bgrm import main
  File "/home/user/Applications/bgrm/bgrm/bgrm.py", line 8, in <module>
    pkg_resources.require("opencv-python<=4.4.0.46")
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 772, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'opencv-python<=4.4.0.46' distribution was not found and is required by the application
```

However, when I try to install it manually, it the requirement appears as satisfied:

```
sudo /home/user/Applications/bgrm/.venv/bin/python -m pip install opencv-python
Requirement already satisfied: opencv-python in ./.venv/lib64/python3.8/site-packages (4.4.0.46)
Requirement already satisfied: numpy>=1.17.3 in ./.venv/lib64/python3.8/site-packages (from opencv-python) (1.21.3)
```

So now I'm not too sure what to do anymore, any ideas would be helpful!

And last but not least: thanks a lot for doing this!

**Comment by athyla** [comment] 2021-11-29 10:37
Hello! 

I've tried again the latest version, cloning it totally fresh. 
I have the same `xcb` problem as before, for which unfortunately I could not find a solution.
To avoid `xcb`, I have tried out the `--disable_window` option and I got the following output:
```

user@machine:~/Applications/bgrm> sudo ./bgrm.sh --blur --disable_window
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/attila/Applications/bgrm/bgrm/__main__.py", line 4, in <module>
    main()
  File "/home/attila/Applications/bgrm/bgrm/bgrm.py", line 28, in main
    formatVirtualCamera(settings, virtCam, cam)
  File "/home/attila/Applications/bgrm/bgrm/bgrm.py", line 66, in formatVirtualCamera
    ioctl(virtCam, VIDIOC_S_FMT, format)
OSError: [Errno 25] Inappropriate ioctl for device

```
Any ideas about this `OSError: [Errno 25] Inappropriate ioctl for device`?

Thanks!

**Comment by blueOkiris** [comment] 2021-11-29 16:03
That was smart to disable the window. I probably should have thought of and suggested that since the problem before was with the gui.

Anyway, the new issue sounds to me like you may be using the wrong input camera.
Default is 0 (/dev/video0), but you can set it with one of the tags (`-c/--camera`). To check what video devices you have do `ls /dev | grep video`

**Comment by athyla** [comment] 2021-11-29 16:14
I have the following camera indexes: 0, 1, 10 and 2.
Every index except the default one gives the following output:
```

user@machine:~/Applications/bgrm> sudo ./bgrm.sh --blur --disable_window -c 2
[ WARN:0] global /tmp/pip-req-build-v1rk7obu/opencv/modules/videoio/src/cap_v4l.cpp (893) open VIDEOIO(V4L2:/dev/video2): can't open camera by index
Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/user/Applications/bgrm/bgrm/__main__.py", line 4, in <module>
    main()
  File "/home/user/Applications/bgrm/bgrm/bgrm.py", line 27, in main
    with Cam(settings) as cam, open('/dev/video10', 'wb') as virtCam:
  File "/home/user/Applications/bgrm/bgrm/cam.py", line 22, in __init__
    _height, _width, self.channels = baseFrame.shape
AttributeError: 'NoneType' object has no attribute 'shape'
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.

```

**Comment by blueOkiris** [comment] 2021-11-29 16:24
Yeah, that's not the issue then; 0 is the correct one if the others give that output.

I'm unsure then what the issue is, but one thing that can cause OpenCV ioctl errors might be a missing dependency for ffmpeg. It is trying to format the video stream properly to create a virtual camera, so that could make sense

Do you have that installed? I don't have it as a dependency, so if that fixes it, I need to add it to the list.

**Comment by athyla** [comment] 2021-11-29 17:57
Yes, I have ffmpeg 4 installed.
I have also tried out installing 2 python packages relating to ffmpeg, but it did not help: python39-ffmpeg-python and python39-imageio-ffmpeg.

**Comment by blueOkiris** [comment] 2022-11-11 21:34
Closing bc old

**Closed** 2022-11-11 21:34 UTC

**Comment by athyla** [comment] 2022-11-16 08:09
Hey blueOkiris!

Thanks for responding to this even after such a long time. You are right, I did not solve this problem and after trying a few other solution for Linux, I gave up.

After your message, I have retried `bgrm` following the updated `readme`, without building it, just installing it with `pip`. It installed fine, but when I try to execute it, it throws an error:
```
python3.8 -m bgrm -b ~/Pictures/bkg.png -w 320 -H 240 -s 2.0
```
```
Traceback (most recent call last):
  File "/usr/lib64/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/attila/.local/lib/python3.8/site-packages/bgrm/__main__.py", line 1, in <module>
    from bgrm.bgrm import main
  File "/home/attila/.local/lib/python3.8/site-packages/bgrm/bgrm.py", line 10, in <module>
    from bgrm.settings import AppSettings
  File "/home/attila/.local/lib/python3.8/site-packages/bgrm/settings.py", line 9, in <module>
    class AppSettings:
  File "/home/attila/.local/lib/python3.8/site-packages/bgrm/settings.py", line 16, in AppSettings
    fill_color: tuple[float, float, float]
TypeError: 'type' object is not subscriptable

```

Any ideas?

**Comment by blueOkiris** [comment] 2022-11-16 08:59
At first glance, my guess is it would be some sort of version thing like maybe 'tuple' wasnt introduced as a type name for data classes yet or something, but I'm not sure.

I see python 3.8, but can you give me the full version name via `python3.8 --version` so I can try to reproduce and see if that's the issue?

**Comment by blueOkiris** [comment] 2022-11-16 09:03
It appears to have been introduced in [PEP 585](https://peps.python.org/pep-0585/), so I probably just need to manual import the Typing module if I want to support python 3.8

**Comment by athyla** [comment] 2022-11-16 14:32
Pfff... it seems that I have a mess on my machine. 
`Python3.8` version is: `3.8.15`, but I also have `python` that defaults to version `2.7.18` and then I have `python3` that defaults to python `3.10.8`, but I also have `python3.8` and `3.9`, just to make things more complicated :(
`pip` was defaulting to `python3.8`, although the `3.9` and `3.10` versions are also installed.

It's a mess, I need to tidy it up. Would it be okay to run `bgrm` with the latest `python3`? (`3.10.8`)

**Comment by blueOkiris** [comment] 2022-11-16 17:17
That's a cool idea for a feature. It would definitely be possible. I'll look into adding it when I get a chance

**Comment by blueOkiris** [comment] 2022-11-16 18:54
Also, I don't know if you're using it or not, but there's a great little tool for managing multiple python versions called [pyenv](https://www.tecmint.com/pyenv-install-and-manage-multiple-python-versions-in-linux/)

I typically have whatever the most recent version of python is installed via my system, and then I'll have pyenv have python 3.8 and maybe 3.7. I use it a lot more for my job than than personal stuff tho
